from SonarPythonAnalyzerFakeStub import CustomStubBase
from typing import Any

class App(CustomStubBase):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def function(self, *args: Any, **kwargs: Any) -> Any: ...
